# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2
#os: unstable

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
  - Win32
  - x64

# specify custom environment variables
environment:
  BOOST_ROOT: C:\Libraries\boost
  BOOST_LIBRARYDIR_WIN32: C:\Libraries\boost\lib32-msvc-12.0
  BOOST_LIBRARYDIR_WIN64: C:\Libraries\boost\lib64-msvc-12.0
# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\mfast

# branches to build
branches:
  #whitelist
  only:
    - master
  # blacklist
  # except:
  #   - gh-pages

# scripts that run after cloning repository
install:
  - cmd: git submodule update --init --recursive
  # - cmd: choco install doxygen.install

# scripts to run before build
before_build:
  - cmd: cd C:\projects\mfast
  - cmd: md build
  - cmd: cd build
  # We generate project files for Visual Studio 12 because the boost binaries installed on the test server are for Visual Studio 12.
  - cmd: if "%platform%"=="Win32" cmake -G "Visual Studio 12" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR_WIN32%" -DBoost_USE_STATIC_LIBS="ON" ..
  - cmd: if "%platform%"=="x64" cmake -G "Visual Studio 12 Win64" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR_WIN64%" -DBoost_USE_STATIC_LIBS="ON" ..

build:
  project: C:\projects\mfast\build\mfast.sln

test_script:
  - cmd: ctest -C %configuration% -VV
